language: python
python:
- '3.6'
install:
- pip3 install -r requirements.txt
before_script:
- export FLASK_APP='application.py'
- export FLASK_DEBUG=1
script:
- python3 tests.py
env:
  secure: JEYwH64+DbRImXh9iFW9NauGg/w58ZnoRLSXgTM2rpcSZYaUFqaikyBhRr4rlSSMxqrSB2ymidrhs6MZVkasRWTnUgB7Ljid3poTBYZ3C1nHz8SaSSLfrJv6S7gzgHJjMj67/NhDV+NPS/Z2Kt/p4t601ePm/etc+53N9vP3lTOVP7CK7PC82SfjX95RO9HKGVxfanyE7SeEYprYJ3XTlp3yvn6kKvo8vVCmUT5hCeKbx1TIeYhzDL2bT3n64RPQyOHVI0L8F+Or1D0Yt053i9ZBpXWKISCKlI1OZ8psPSa0HtnoFG8zKwta+wEJZxwYnURpcpe6SRqOGxY7hKnilg3OdMmrIGDDb/A+9/Sgq4mnEAhzFpvipGNfVFkKJ7QdO9ysQyoP+Ak/xL7hc15porSV8Qcw7KmIYpea+m+vSCeFlIrItrE6gIPzy1W+OOfYOB2fqsAPXAPk6nMpIsfLjTis49PbHZTCNFrX74k739f9BKvJKUhMm20afl/MVOShSVZbEv9m5VtnwRT5DGDwQGH1BuV9OFm3jo1u3fd+SHCdC3grc577H/fulVYaRjZsWTpB+wS/bEymU7q/IuGTEiN1/It7TJKYWp96RPtv9k4ggIaxfmyN3qlyUogzwAXCn9DB23Snh18D46iRz1x3uFV97of08MU9iavR0Fc6huE=
