version: '3'

services:
  db:
    image: postgres
    env_file:
      - docker.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: gunicorn -w 4 --bind 0.0.0.0 thetextinbox.application
    env_file:
      - docker.env
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
